apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: http://keycloak:8080
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_ID
              value: users-microservice
            - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_URI
              value: http://users-microservice:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]
              value: Path=/api/users/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]
              value: StripPrefix=1
            - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_ID
              value: games-microservice
            - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_URI
              value: http://games-microservice:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]
              value: Path=/api/games/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]
              value: StripPrefix=1
            - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_ID
              value: lobby-microservice
            - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_URI
              value: http://lobby-microservice:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]
              value: Path=/api/lobbies/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]
              value: StripPrefix=1
            - name: SPRING_CLOUD_GATEWAY_ROUTES[3]_ID
              value: keycloak-auth
            - name: SPRING_CLOUD_GATEWAY_ROUTES[3]_URI
              value: http://keycloak:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]
              value: Path=/auth/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES[4]_ID
              value: lobby-websocket
            - name: SPRING_CLOUD_GATEWAY_ROUTES[4]_URI
              value: http://lobby-microservice:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES[4]_PREDICATES[0]
              value: Path=/lobby/ws/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES[4]_FILTERS[0]
              value: StripPrefix=1
            - name: SPRING_CLOUD_GATEWAY_ROUTES[5]_ID
              value: games-websocket
            - name: SPRING_CLOUD_GATEWAY_ROUTES[5]_URI
              value: http://games-microservice:8080
            - name: SPRING_CLOUD_GATEWAY_ROUTES[5]_PREDICATES[0]
              value: Path=/games/ws/**
            - name: SPRING_CLOUD_GATEWAY_ROUTES[5]_FILTERS[0]
              value: StripPrefix=1




---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: microservices
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort